# noinspection SqlNoDataSourceInspectionForFile
# --- !Ups

INSERT INTO sendgrid_email_templates(name, template_id, subject, body_html, body_text, is_deleted, creation_date, last_modification_date) VALUES ('account-activation', 'xxx','Activate email', '<h2 style=\"font-weight:bold;;font-size:15px;;\">&iexcl;;Hola *|USERNAME|*!</h2> <p style=\"font-size:14px;;\"> Te hemos enviado este email para poder corroborar tu casilla de correo. La misma la necesitar&aacute;;s para ciertas actividades dentro del sitio, por lo que te recomendamos hacerlo ahora.<br/>Para activarla presiona <a style=\"color:#308060;;\" href=\"*|ACTIVATION_URL|*\">aqu&iacute;;</a>. </p> <br/> <p style=\"font-size:14px;;\">Saludos,</p> <p style=\"font-size:14px;;\">Hackathon Starter</p>', 'Hola *|USERNAME|* \n Te hemos enviado este email para poder corroborar tu casilla de correo. La misma la necesitarás para ciertas actividades dentro del sitio, por lo que te recomendamos hacerlo ahora. Para activarla presiona *|ACTIVATION_URL|* \n Saludos, \n Hackathon Starter', false, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO sendgrid_email_templates(name, template_id, subject, body_html, body_text, is_deleted, creation_date, last_modification_date) VALUES ('password-reset', 'yyy', 'Reset password', '<h2 style=\"font-weight:bold;;font-size:15px;;\">Hola *|USERNAME|*,</h2> <p style=\"font-size:14px;;\"> Has pedido restablecer la contraseña de tu cuenta. Puedes establecer una nueva contrase&ntilde;;a haciendo click en este enlace: <br><br> <a style=\"color:#308060;;\" href=\"*|RESETPASS_URL|*\">*|RESETPASS_URL|*</a> <br><br> Si no has solicitado un cambio de contrase&ntilde;;a, puedes ignorar este mensaje y tu contrase&ntilde;;a se mantendr&aacute;; sin cambios. </p><br><p style=\"font-size:14px;;\">Saludos, </p> <p style=\"font-size:14px;;\">Hackathon Starter</p>', 'Hola *|USERNAME|*, \n Has pedido restablecer la contraseña de tu cuenta. Puedes establecer una nueva contraseña haciendo click en este enlace: \n *|RESETPASS_URL|* \n Si no has solicitado un cambio de contraseña, puedes ignorar este mensaje y tu contraseña se mantendrá sin cambios. Saludos, \n Hackathon Starter', false, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());

INSERT INTO admin_roles (name, description, is_deleted, creation_date, last_modification_date) VALUES ('ADMIN', 'Admin Role', false, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO admin_roles (name, description, is_deleted, creation_date, last_modification_date) VALUES ('OPS', 'Ops Role', false, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());

-- Admin Pwd: &rX3uZAwGE7JyuBW]h?{JX
INSERT INTO admin_users (name, username, password, is_deleted, creation_date, last_modification_date) VALUES ('Admin', 'admin', '$2a$10$rB7e/.jt8GZzpuCz60BF3u3Ui.XKBEgWPj7K/W49OaWCfZd01HiK.', false, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());

INSERT INTO admin_users_roles (admin_user_id, admin_role_id, is_deleted, creation_date, last_modification_date) VALUES((SELECT id from admin_users where username = 'admin'), (SELECT id from admin_roles where name = 'ADMIN'), false, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
# --- !Downs
